-- MySQL Script generated by MySQL Workbench
-- 09/16/15 21:31:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MERGourmet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MERGourmet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MERGourmet` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MERGourmet` ;

-- -----------------------------------------------------
-- Table `MERGourmet`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MERGourmet`.`Menu` (
  `idMenu` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nome` VARCHAR(45) NOT NULL COMMENT '',
  `Categoria` VARCHAR(20) NOT NULL COMMENT '',
  `Preco` DECIMAL(5,2) NOT NULL COMMENT '',
  `Tempo` VARCHAR(10) NOT NULL COMMENT '',
  `Pontos` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idMenu`)  COMMENT '',
  UNIQUE INDEX `idMenu_UNIQUE` (`idMenu` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERGourmet`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MERGourmet`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idMesa` INT NOT NULL COMMENT '',
  `idFidelidade` INT NOT NULL COMMENT '',
  `Data` DATE NOT NULL COMMENT '',
  `Hora` TIME NOT NULL COMMENT '',
  `Status` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`idPedido`, `idMesa`, `idFidelidade`)  COMMENT '',
  UNIQUE INDEX `idMesa_UNIQUE` (`idMesa` ASC)  COMMENT '',
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC)  COMMENT '',
  UNIQUE INDEX `idFidelidade_UNIQUE` (`idFidelidade` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERGourmet`.`MenuIngrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MERGourmet`.`MenuIngrediente` (
  `idMenu` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Ingrediente` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idMenu`)  COMMENT '',
  UNIQUE INDEX `idIngrediente_UNIQUE` (`idMenu` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERGourmet`.`Fidelidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MERGourmet`.`Fidelidade` (
  `idFidelidade` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idPrivilegio` INT NOT NULL COMMENT '',
  `Cliente` VARCHAR(45) NOT NULL COMMENT '',
  `Data` DATE NOT NULL COMMENT '',
  `Email` VARCHAR(60) NOT NULL COMMENT '',
  `Pontos` INT NOT NULL COMMENT '',
  `Usuario` VARCHAR(15) NOT NULL COMMENT '',
  `Senha` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idFidelidade`, `idPrivilegio`)  COMMENT '',
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC)  COMMENT '',
  UNIQUE INDEX `idFidelidade_UNIQUE` (`idFidelidade` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERGourmet`.`ItemPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MERGourmet`.`ItemPedido` (
  `idItem` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idPedido` INT NOT NULL COMMENT '',
  `idMenu` INT NOT NULL COMMENT '',
  `Quantidade` INT NOT NULL COMMENT '',
  `Preco` DECIMAL(5,2) NOT NULL COMMENT '',
  `HoraEntrega` TIME NULL COMMENT '',
  PRIMARY KEY (`idItem`, `idPedido`, `idMenu`)  COMMENT '',
  UNIQUE INDEX `idItem_UNIQUE` (`idItem` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MERGourmet`.`Privilegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MERGourmet`.`Privilegio` (
  `idPrivilegio` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Privilegio` VARCHAR(10) NOT NULL COMMENT '',
  `Descricao` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idPrivilegio`)  COMMENT '',
  UNIQUE INDEX `idPrivilegio_UNIQUE` (`idPrivilegio` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
